# Generated by Django 4.1.2 on 2022-10-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('SerialNo', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=50)),
                ('EmailID', models.CharField(max_length=50)),
                ('DOB', models.DateField(null=True)),
                ('PhoneNO', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=40)),
                ('Address', models.CharField(max_length=300)),
                ('UserStatus', models.CharField(max_length=50)),
                ('ImageName', models.CharField(max_length=50)),
            ],
        ),
    ]
