# Generated by Django 4.1.2 on 2022-10-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamneo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='SerialNo',
            new_name='RandomID',
        ),
    ]
